export interface IUser {
    name: string,
    birth: string,
    height: number,
    weight: number,
    obstacle: string,
    goal: string,
    period: string,
    birthControl: string,
    energy: string,
    workoutFrequency: number,
    referral: string,
    howFound: string,
    createdAt: string,
    updatedAt: string,
}